export const ActionTypes = {

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_FAILURE: 'LOGIN_REQUEST_FAILURE',
  LOGIN_REQUEST_RESTART:'LOGIN_REQUEST_RESTART',
  RESTART_LOGIN_REQUEST:'RESTART_LOGIN_REQUEST',
  LOG_OUT_REQUEST: 'LOG_OUT_REQUEST',

  REGISTER_REQUEST:'REGISTER_REQUEST',
  REGISTER_REQUEST_SUCCESS:'REGISTER_REQUEST_SUCCESS',
  REGISTER_REQUEST_FAILURE:'REGISTER_REQUEST_FAILURE',
  REGISTER_RESET_REQUEST:'REGISTER_RESET_REQUEST',


  VERIFY_REQUEST: 'VERIFY_REQUEST',
  VERIFY_REQUEST_SUCCESS: 'VERIFY_REQUEST_SUCCESS',
  VERIFY_REQUEST_FAILURE: 'VERIFY_REQUEST_FAILURE',
  UPDATE_TOKEN:'UPDATE_TOKEN',


  GET_PRODUCT_CATOG_REQUEST: 'GET_PRODUCT_CATOG_REQUEST',
  GET_PRODUCT_CATOG__SUCCESS: 'GET_PRODUCT_CATOG__SUCCESS',
  GET_PRODUCT_CATOG_FAILURE: 'GET_PRODUCT_CATOG_FAILURE',

  FETCH_LOGIN_USER_REQUEST: 'FETCH_LOGIN_USER_REQUEST',
  FETCH_LOGIN_USER_SUCCESS: 'FETCH_LOGIN_USER_SUCCESS',
  FETCH_LOGIN_USER_FAILURE: 'FETCH_LOGIN_USER_FAILURE',

  FETCH_USER_ADDRESS_REQUEST: 'FETCH_USER_ADDRESS_REQUEST',
  FETCH_USER_ADDRESS_SUCCESS: 'FETCH_USER_ADDRESS_SUCCESS',
  FETCH_USER_ADDRESS_FAILURE: 'FETCH_USER_ADDRESS_FAILURE',

  ADD_ADDRESS_REQUEST: 'ADD_ADDRESS_REQUEST',
  ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
  ADD_ADDRESS_FAILURE: 'ADD_ADDRESS_FAILURE',
  ADD_ADDRESS_DONE: 'ADD_ADDRESS_DONE',

  UPDATE_USER_ADDRESS_REQUEST: 'UPDATE_USER_ADDRESS_REQUEST',
  UPDATE_USER_ADDRESS_SUCCESS: 'UPDATE_USER_ADDRESS_SUCCESS',
  UPDATE_USER_ADDRESS_FAILURE: 'UPDATE_USER_ADDRESS_FAILURE',

  FETCH_ORDERHISTORY_REQUEST: 'FETCH_ORDERHISTORY_REQUEST',
  FETCH_ORDERHISTORY_SUCCESS: 'FETCH_ORDERHISTORY_SUCCESS',
  FETCH_ORDERHISTORY_FAILURE: 'FETCH_ORDERHISTORY_FAILURE',

  UPDATE_LOGIN_USER_REQUEST: 'UPDATE_LOGIN_USER_REQUEST',
  UPDATE_LOGIN_USER_SUCCESS: 'UPDATE_LOGIN_USER_SUCCESS',
  UPDATE_LOGIN_USER_FAILURE: 'UPDATE_LOGIN_USER_FAILURE',

  FETCH_ACC_STATUS_REQUEST: 'FETCH_ACC_STATUS_REQUEST',
  FETCH_ACC_STATUS_SUCCESS: 'FETCH_ACC_STATUS_SUCCESS',
  FETCH_ACC_STATUS_FAILURE: 'FETCH_ACC_STATUS_FAILURE',

  UPDATE_ACC_STATUS_REQUEST: 'UPDATE_ACC_STATUS_REQUEST',
  UPDATE_ACC_STATUS_SUCCESS: 'UPDATE_ACC_STATUS_SUCCESS',
  UPDATE_ACC_STATUS_FAILURE: 'UPDATE_ACC_STATUS_FAILURE',

  FETCH_PAGEBYNAME_REQUEST: 'FETCH_PAGEBYNAME_REQUEST',
  FETCH_PAGEBYNAME_SUCCESS: 'FETCH_PAGEBYNAME_SUCCESS',
  FETCH_PAGEBYNAME_FAILURE: 'FETCH_PAGEBYNAME_FAILURE',

  VERIFY_WITH_REFRESH_REQUEST: 'VERIFY_WITH_REFRESH_REQUEST',
  VERIFY_WITH_REFRESH_SUCCESS: 'VERIFY_WITH_REFRESH_SUCCESS',
  VERIFY_WITH_REFRESH_FAILURE: 'VERIFY_WITH_REFRESH_FAILURE',

  CONTACT_US_REQUEST: 'CONTACT_US_REQUEST',
  CONTACT_US_SUCCESS: 'CONTACT_US_SUCCESS',
  CONTACT_US_FAILURE: 'CONTACT_US_FAILURE',
  CONTACT_US_RESET: 'CONTACT_US_RESET',

  GET_CONTACT_US_REQUEST: 'GET_CONTACT_US_REQUEST',
  GET_CONTACT_US_SUCCESS: 'GET_CONTACT_US_SUCCESS',
  GET_CONTACT_US_FAILURE: 'GET_CONTACT_US_FAILURE',



  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
  CLEAR_CART_REQUEST:'CLEAR_CART_REQUEST',
GET_CART_REQUEST: 'GET_CART_REQUEST',
GET_CART_SUCCESS: 'GET_CART_SUCCESS',
GET_CART_FAILURE: 'GET_CART_FAILURE',



  INCREMENT_QUANTITY:'INCREMENT_QUANTITY',
  DECREMENT_QUANTITY:'DECREMENT_QUANTITY',

    PLACE_ORDER_REQUEST:'PLACE_ORDER_REQUEST',
    PLACE_ORDER_SUCCESS:'PLACE_ORDER_SUCCESS',
    PLACE_ORDER_FAILURE:'PLACE_ORDER_FAILURE',
    PAYMENT_VERIFICATION_SUCCESS:'PAYMENT_VERIFICATION_SUCCESS',
    PAYMENT_VERIFICATION_FAILURE:"PAYMENT_VERIFICATION_FAILURE"
};
